version: '3.9'
services:
  dind: 
    image: docker:dind
    privileged: true
    container_name: dind
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports: [2367:2367]
    networks: [jenkins]
    command: --storage-driver=overlay2
#############################################################
  jenkins:
    privileged: true
    depends_on:
      - dind
    user: root
    build: ./
    # image: "jenkins/jenkins:2.375.1"
    container_name: jenkins-blueocean 
    environment:
      - DOCKER_HOST=tcp://dind:2375
      # - DOCKER_CERT_PATH=/certs/client
      # - DOCKER_TLS_VERIFY=1
    ports: [8080:8080, 50000:5000]
    networks: [jenkins]
    restart: on-failure
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
#############################################################
networks:
  jenkins:
volumes:
  jenkins-data:
  jenkins-docker-certs: