pipeline {
    agent any

    stages {
        stage('Cloning') {
            steps {
                git url:'https://github.com/InzynieriaOprogramowaniaAGH/MDO2023.git', branch: 'KW403352'
            }
        }
        stage('Building') {
            steps {
                sh 'docker build GCL3/KW403352/lab2/build/Dockerfile --tag build'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker build GCL3/KW403352/lab2/test/Dockerfile --tag test'
            }
        }
    }
}
