pipeline {
    agent any

    environment {     
        DOCKERHUB_CREDENTIALS=credentials('DOCKERHUB')     
    }   

    stages {
        stage('Collect') {
            steps {
                echo "--- COLLECT ---"
                git url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2023.git',
                branch: 'SS403799'
            }
        }
        stage('Build') {
            steps {
                echo '--- BUILD ---'
                sh 'docker build -f GCL3/SS403799/Lab2/Dockerfile -t makesitebuild .'
            }
        }
        stage('Test') {
            steps {
                echo '--- TEST ---'
                sh 'docker build -f GCL3/SS403799/Lab2/Dockerfile.test -t makesitebuild .'
            }
        }
        stage('Publish') {
            steps {
                echo '--- PUBLISH ---'
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin' 
                sh 'docker build -f GCL3/SS403799/Lab2/Dockerfile.publish -t szymonsawis/lab3:$BUILD_NUMBER .'
                sh 'docker push szymonsawis/lab3:$BUILD_NUMBER'
            }
        }
    }
    post {
    always {
      sh 'docker logout'
    }
    }
}
