pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: 'PM404085']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2023.git']]])
      }
    }
    stage('Build') {
      steps {

        sh 'sudo docker build -f GCL2/PM404085/lab2/build/Dockerfile -t builder .'
      }
    }
    stage('Test') {
      steps {

		sh 'sudo docker build -f GCL2/PM404085/lab2/test/Dockerfile -t tester .'
      }
    }
  }
}