pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: 'PM404085']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2023.git']]])
      }
    }
    stage('Build') {
      steps {

        sh 'sudo docker build -f GCL2/PM404085/lab2/build/Dockerfile -t builder .'
      }
    }
    stage('Test') {
      steps {

		sh 'sudo docker build -f GCL2/PM404085/lab2/test/Dockerfile -t tester .'
      }
    }
	
	stage('Deploy') {
    steps {
		dir("GCL2/PM404085/lab2/build") {
			def dockerImage
			sh 'dockerImage = sudo docker build -t my-image .'
			
			withCredentials([usernamePassword(credentialsId: 'ab244b3c-bdfd-4729-bf50-6784265def3b', usernameVariable: 'MY_USERNAME', passwordVariable: 'MY_PASSWORD')]) {
				sh 'sudo docker login -u $MY_USERNAME -p $MY_PASSWORD'
				sh 'sudo dockerImage.push()'
			}

		}
    }
}
  }
}