pipeline {
  agent any
  stages {
    stage('Dependencies') {
      steps {
        git(
                url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2023.git',
                branch: 'PM404085'
            )
      }
    }
    stage('Build') {
      steps {
        sh 'docker build -f GCL2/PM404085/lab2/build/dockerfile -t builder .'
      }
    }
    stage('Test') {
      steps {
		sh 'docker build -f GCL2/PM404085/lab2/test/dockerfile -t tester .'
      }
    }
  }
}