FROM lab3_base

RUN git clone https://github.com/bezkoder/spring-boot-unit-test-rest-controller.git
RUN chmod -R 777 spring-boot-unit-test-rest-controller
WORKDIR /spring-boot-unit-test-rest-controller
CMD [ "tail","-f","/dev/null"]