pipeline {
    agent any

    stages {
		stage('Checkout') {
		  steps {
			checkout([$class: 'GitSCM', branches: [[name: 'AB290984']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2023.git']]])
		  }
		}
        stage('Build') {
            steps {
                sh 'docker build -f GCL1/AB290984/lab2/Dockerfile -t build321 .'
            }
        }
        stage('Test') {
            steps {
                sh 'docker build -f GCL1/AB290984/lab2/test/Dockerfile -t test321 .'
            }
        }
    }
}
